# Generated by Django 5.0.3 on 2024-03-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diciplina',
            new_name='Disciplina',
        ),
    ]
