# Generated by Django 5.0.3 on 2024-03-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_diciplina_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinaporcurso',
            name='carga_horaria',
        ),
    ]
